---
abstract: 'send SMS with smsc.ru'
author:
  - 'Sergey Zasenko.'
build_requires:
  ExtUtils::MakeMaker: 6.62
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SMS-API-SMSC
no_index:
  directory:
    - inc
    - t
requires:
  LWP::UserAgent: 0
  URI::Escape: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.001
